apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot-test-app1 
  janus-idp.io/tekton: chatbot-test-app1
  backstage.io/kubernetes-id: chatbot-test-app1
  backstage.io/kubernetes-namespace: testns 
  app.kubernetes.io/part-of: chatbot-test-app1
resources: 
- application-dev.yaml