kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chatbot-test-app1-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: chatbot-test-app1-dsp-job
    namespace: testns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chatbot-test-app1-dsp-job-role